### ISSUE TITLE
adding script via the angular way

### ISSUE THREAD

**Issue by zcsongor** [seveves/angular-stencil#4]
Just one question came to my mind: why don't you add the stencil component to the angular project inside the .angular-cli.json?
https://github.com/angular/angular-cli/wiki/stories-global-scripts

Nonetheless, great work!

**Comment by seveves** [comment]
Yes, you're right ... the better way would be using the angular cli config but to demonstrate it was clearer to add it directly. I will add it to the README as a better alternative 👍
